name: Azure Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      DOCKER_REGISTRY: f375a13f.azurecr.io
      DOCKER_IMAGE_NAME_WORDS: words:1.0.3
      DOCKER_IMAGE_NAME_WEB: web:1.0.3
      AZURE_RESOURCE_GROUP_NAME: 064b73c3
      AZURE_APP_NAME_WORDS: b02d6766
      AZURE_APP_NAME_WEB: fbd866b2

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Login to Docker
      uses: docker/login-action@v1
      with:
        registry: ${{ env.DOCKER_REGISTRY }}
        username: ${{ secrets.AZURE_CLIENT_ID }}
        password: ${{ secrets.AZURE_CLIENT_SECRET }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push words image to ACR
      uses: docker/build-push-action@v2
      with:
        context: ./words
        tags: ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME_WORDS }}
        push: true

    - name: Build and push web image to ACR
      uses: docker/build-push-action@v2
      with:
        context: ./web
        tags: ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME_WEB }}
        push: true

    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy words to Container App
      uses: azure/powershell@v1
      with:
        azPSVersion: "latest"
        inlineScript: |
          az extension add --name containerapp --upgrade
          az containerapp update --name ${{ env.AZURE_APP_NAME_WORDS }} --resource-group ${{ env.AZURE_RESOURCE_GROUP_NAME }} --image ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME_WORDS }}

    - name: Deploy web to Container App
      uses: azure/powershell@v1
      with:
        azPSVersion: "latest"
        inlineScript: |
          az containerapp update --name ${{ env.AZURE_APP_NAME_WEB }} --resource-group ${{ env.AZURE_RESOURCE_GROUP_NAME }} --image ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME_WEB }}
